### ISSUE TITLE
Substituir a lib moment

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia-app#18]
Substitui a lib moment.js por uma outra, visto que é uma lib não mais mantida e extremamente grande.

Sugestões: `date-fns` ou `DateTime/Luxon`

**Comment by mateus4k** [comment]
Sugestão: [dayjs](https://github.com/ufersa/plataforma-sabia/blob/d0613c2688973121f28892c35d9747475c71f0bc/packages/api/package.json#L49)
