### ISSUE TITLE
Criar stacks distintas

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia-app#23]
Depende de #21 e #22.

Criar estrutura de stacks distintas:
- Stack de login/cadastro
- Stack "logada"

A ideia é que o usuário possa, ao logar na aplicação, ser redirecionado para a stack logável, **sem a possibilidade de pressionar o botão voltar**. Da mesma maneira, ao deslogar, o componente deve redirecionar para a stack de login.

**Comment by mtullyoc** [comment]
Resolved by PR #26
