### ISSUE TITLE
Detalhes da tecnologia 

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia-app#46]
- [x] Integrar seção de georreferenciamento.

**Comment by davioliveiira** [comment]
@mtullyoc essa faz parte da #61

**Comment by mtullyoc** [comment]
@davioliveiira atualizei essa issue para contemplar apenas o Georreferenciamento.

**Comment by mtullyoc** [comment]
Resolved on PR #93
