### ISSUE TITLE
Perfil do Usuário com dados completos

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia-app#75]
Hoje no app só tem os campos de NOme e email no cadastro de usuário, no entanto, para realizar algumas tarefas no sistema, principalmente de aquisição de tecnologias e serviços é preciso estar com os dados pessoais preenchidos por completo.

![Cadastro usuario app](https://user-images.githubusercontent.com/48101231/110625059-b6a39100-817d-11eb-8e47-e02535a05c74.png)

Para isso, será preciso implementar também no app os campos completos de dados pessoais no cadastro de usuário, contendo:

- NOME COMPLETO
- EMAIL PRINCIPAL
- CPF
- DATA DE NASCIMENTO
- TELEFONE PARA CONTATO
- CEP
- ENDEREÇO
- COMPLEMENTO
- BAIRRO
- CIDADE
- ESTADO
- PAIS

**Comment by JoaoPauloSMoura** [comment]
![Captura de Tela 2021-03-12 às 19 29 17](https://user-images.githubusercontent.com/46350848/111005262-3fcaeb80-8369-11eb-9ae4-b2459f0deb9e.png)
