### ISSUE TITLE
Correções sobre as tecnologias no APP

### ISSUE THREAD

**Issue by nichollasrennah** [ufersa/plataforma-sabia-app#78]
- Nos cards das tecnologias no qual tem a opção is_seller como false **não pode apresentar o preço**, visto que essa tecnologia não está à venda. Mesmo que o preço esteja R$ 0,00. Só apresentar preço se esse campo is_seller for true.
![Screenshot_20210314-090726_Plataforma Sabi](https://user-images.githubusercontent.com/48101231/111068229-b3264780-84a6-11eb-93ee-0facfce7f1cc.jpg)

- Nos detalhes da tecnologia da mesma forma, só apresentar o preço se is_seller for true, senão, deixa em branco esse campo. Tirar a palavra gratuito, visto que ela não está à venda. Gratuito dá a entender que a pessoa pode pedir de graça.
- Para tecnologias que não estão à venda (is_seller false) não mostrar o botão ADQUIRIR TECNOLOGIA (ou ao clicar no botão aparecer um texto "Essa tecnologia não está à venda!").
![Screenshot_20210314-090730_Plataforma Sabi](https://user-images.githubusercontent.com/48101231/111068301-05ffff00-84a7-11eb-8e81-197a572acb5c.jpg)

- Ícones não estão aparecendo.
![Screenshot_20210314-090754_Plataforma Sabi](https://user-images.githubusercontent.com/48101231/111068318-14e6b180-84a7-11eb-9822-c6e6e0d981cf.jpg)

**Comment by davioliveiira** [comment]
@nichollasrennah Resolvido!

**Comment by nichollasrennah** [comment]
@davioliveiira testei agora no app e o botão **Adquirir tecnologia** ainda está levando pra tela de realizar o pedido para tecnologias que não estão à venda. É pra apresentar a mensagem "Essa tecnologia não está disponível para aquisição"
